# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager
# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   controller_names:
#     - L_manipulator_controller
#     - R_manipulator_controller
#     - dual_manipulator_controller

#   L_manipulator_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#       - L_panda_joint1
#       - L_panda_joint2
#       - L_panda_joint3
#       - L_panda_joint4
#       - L_panda_joint5
#       - L_panda_joint6
#       - L_panda_joint7

#   R_manipulator_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#       - R_panda_joint1
#       - R_panda_joint2
#       - R_panda_joint3
#       - R_panda_joint4
#       - R_panda_joint5
#       - R_panda_joint6
#       - R_panda_joint7

#   dual_manipulator_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#       - L_panda_joint1
#       - L_panda_joint2
#       - L_panda_joint3
#       - L_panda_joint4
#       - L_panda_joint5
#       - L_panda_joint6
#       - L_panda_joint7
#       - R_panda_joint1
#       - R_panda_joint2
#       - R_panda_joint3
#       - R_panda_joint4
#       - R_panda_joint5
#       - R_panda_joint6
#       - R_panda_joint7
